language: node_js
node_js:
   - 0.10
language: python
python:
   - "2.7"
   - "3.3"
install:
   - pip install pika --use-mirrors
   - pip install nose-cov --use-mirrors
# command to install dependencies
#install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: make test